/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MeetingNotesRouteImport } from './routes/meeting-notes'
import { Route as IndexRouteImport } from './routes/index'

const MeetingNotesRoute = MeetingNotesRouteImport.update({
  id: '/meeting-notes',
  path: '/meeting-notes',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meeting-notes': typeof MeetingNotesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meeting-notes': typeof MeetingNotesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meeting-notes': typeof MeetingNotesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meeting-notes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meeting-notes'
  id: '__root__' | '/' | '/meeting-notes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetingNotesRoute: typeof MeetingNotesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/meeting-notes': {
      id: '/meeting-notes'
      path: '/meeting-notes'
      fullPath: '/meeting-notes'
      preLoaderRoute: typeof MeetingNotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetingNotesRoute: MeetingNotesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
